### ISSUE TITLE
Can't find/build settings.c

### ISSUE THREAD

**Issue by shtrom** [revk/Watchy#1]
I'm trying to build this to try it out.

When running `cmake .`, it seems happy, but ends up failing with the following error:
```
CMake Error at /opt/esp-idf/tools/cmake/component.cmake:480 (add_library):
  Cannot find source file:

    /home/shtrom/src/revk-Watchy/settings.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  /opt/esp-idf/tools/cmake/component.cmake:653 (idf_component_register)
  main/CMakeLists.txt:3 (register_component)


CMake Error at /opt/esp-idf/tools/cmake/component.cmake:480 (add_library):
  No SOURCES given to target: __idf_main
Call Stack (most recent call first):
  /opt/esp-idf/tools/cmake/component.cmake:653 (idf_component_register)
  main/CMakeLists.txt:3 (register_component)
```

I see there's a `settings.def`, but I'm not sure how to build a C file from that.

Any advice as to how to proceed to build would be welcome (:

I have `esp-idf` 5.3-1 installed on ArchLinux from https://aur.archlinux.org/packages/esp-idf, and `$IDF_PATH` is set.

**Comment by revk** [comment]
It should make `settings.h` and `settings.c`?

Ah, don't run `cmake`, run `make`, that will build `settings.c`

**Comment by shtrom** [comment]
Yup, that looks better. Now I need your secure boot private key q:

**Comment by revk** [comment]
You can make your own, or disable it. Best of luck.
